root: true
env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  block-scoped-var:
    - error
  curly:
    - error
    - all
  eqeqeq:
    - error
    - always
  no-multi-spaces:
    - error
  strict:
    - error
  no-unused-vars:
    - error
  no-undef:
    - error
  callback-return:
    - error
  block-spacing:
    - error
    - never
